CREATE VIEW [dbo].[V_Film]
AS SELECT [FilmId]
      ,[Title]
      ,[Description]
      ,[ReleaseYear]
      ,[F].[LanguageId]
	  ,[L].[Name]
      ,[RentalDuration]
      ,[RentalPrice]
      ,[Length]
      ,[ReplacementCost]
	  ,[F].[RatingId]
      ,[Rating]
  FROM [Film] AS [F]
  JOIN [Rating] AS [R] ON [F].[RatingId] = [R].[RatingId]
  JOIN [Language] AS [L] ON [F].[LanguageId] = [L].[LanguageId]
